FROM amazoncorretto:11
COPY target/pokemonAPI-0.0.1-SNAPSHOT.jar pokemonAPI-0.0.1.jar
COPY src/main/resources/pokemonConId.json src/main/resources/pokemonConId.json
CMD ["java","-jar","pokemonAPI-0.0.1.jar"]